name: Python CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # This is required to push changes back to the repository
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: pip install uv

      - name: Cache uv dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Create Virtual Environment
        run: uv venv

      - name: Install dependencies
        run: uv pip install -e .[dev]

      - name: Lint and Auto-fix with ruff
        run: |
          uv run ruff check . --fix
          uv run ruff format .

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # Check if there are any changes to commit
          if ! git diff --quiet; then
            git add -A
            git commit -m "style: Auto-fix linting errors"
            git push
          else
            echo "No linting changes to commit."
          fi

      - name: Run tests with pytest
        run: |
          uv run pytest
